/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.techtribedev.NICSimulation;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class App {

    public static void main(String[] args) throws InterruptedException {
        try {
            //Simulation.startSimulation = true;
            DebugMode.isDebugModeEnabled = true;
            Router routerGwDhcp = new Router("cisco", 4, true);
            Computer computer1 = new Computer(true, "synopsis");
            Computer computer2 = new Computer(true, "cadence");
            UtpWire uw0 = new UtpWire(computer1.getEthPort(), routerGwDhcp.getLan1());
            UtpWire uw1 = new UtpWire(computer2.getEthPort(), routerGwDhcp.getLan2() );
            routerGwDhcp.connectPorts(uw0);
            System.out.println();
            routerGwDhcp.connectPorts(uw1);
            
            //Stop Simulation
            Thread.sleep(5000);
            routerGwDhcp.getDhcpServer().stopDhcp();
            routerGwDhcp.getDhcpServer().interrupt();
            
            System.out.println();
            routerGwDhcp.displayRoutersInfo();
            computer1.displayInfo();
            computer2.displayInfo();
            System.exit(0);
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
