/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.techtribedev.NICSimulation;

public class App {

    public static void main(String[] args) {
        Router r0 = new Router("Microtik", 10);
        Router r1 = new Router("Cisco",10);
        UtpWire w0 = new UtpWire(r1.getOutWan(), r0.getInWan());
        
        int CODE = r1.connectPorts(w0);
        System.out.println("Finished with code: " + CODE);
       

        r0.displayRoutersInfo();
        r1.displayRoutersInfo();
       
    }
}
